### ISSUE TITLE
violation of the Dependency Rule principle

### ISSUE THREAD

**Issue by Yeroshin** [chrisbanes/tivi#1050]
The domain layer violates the Dependency Rule and imports classes from the data layer. It's strange that an android expert writes such code.

**Comment by chrisbanes** [comment]
lol, there are no laws here.

It’s strange that someone felt the need to create an issue like so.

**Comment by Yeroshin** [comment]
when someone tells me that I have a bad code, I will say that you have not seen the android experts code yet and show this dialog. Now the phrase - there are no rules here - is my favorite. Thank you very much)))

**Comment by chrisbanes** [comment]
To give you a longer answer:

Tivi is as started roughly 5/6 years ago and the 'current' architecture guidance has changed a **lot** in that time.

Re-reading your comment, I'm not sure I understand what the issue is? Tivi (mostly) follows the official [architecture guidance](https://developer.android.com/topic/architecture/domain-layer). In fact, it pre-dates that guidance.

**Comment by Yeroshin** [comment]
Uncle Bob's guide predates this guide, which predates the official architecture guide. Or did you come up with this architecture yourself? when the domain layer depends on other layers, the whole meaning of the architecture is lost. The Dependency Rule tells us that the inner layers should not depend on the outer ones and allows us to build systems that will be easier to maintain, because changes in the outer layers will not affect the inner layers. In search of a reference project, I turned to experts and in the end I explain the basic things myself.

**Comment by Yeroshin** [comment]
can you add me as a friend on linkedin please?
