### ISSUE TITLE
CI/CD: Could you please explain your strategy?

### ISSUE THREAD

**Issue by ursusursus** [chrisbanes/tivi#540]
Hi, I'm looking at your github action workflows, and was wondering what is your release strategy

In general I see on every push you run
`- name: Build debug and check`

but then
```
name: Build release
if: github.ref != 'refs/heads/master'
run: ./gradlew bundleRelease assembleRelease -Ptivi.versioncode=$BUILD_NUMBER --scan

- name: Publish to Play Store
if: github.ref == 'refs/heads/master'
run: ./gradlew publishRelease -Ptivi.versioncode=$BUILD_NUMBER --scan
```
Which confuse me. Are you building release apk for every non master commit, and deploying a release on every commit in master?

Also, I was wondering how could I ssh my signing keystore into the CI server but thats probably moot point, and I see you have them checked in just encrypted, and keys from that are in github secrets, correct? Also they keys from the keystore are there too?

**Comment by chrisbanes** [comment]
Yeah the task names could be improved.

> Are you building release apk for every non master commit, and deploying a release on every commit in master?

Yep, exactly. The reason for the 2 different tasks is just because I only want to deploy to the Play Store (internal testing track) for every commit to `master`. For topic branches and PRs, I just want to make sure that `assembleRelease` succeeds.

I could set up a nightly push to Play instead of deploying-on-commit, but I actually like the quick iteration of deploying to the internal testing track (which is just for me basically). When ready, I then promote a build to alpha, etc.

> I see you have them checked in just encrypted, and keys from that are in github secrets, correct? Also they keys from the keystore are there too?

Exactly, they’re encrypted with OpenSSL. The passphrase is in GitHub secrets, and is used to decrypt the keystore (and other private auth files). The keystore passwords are also in GitHub secrets.

**Comment by ursusursus** [comment]
Understood thanks.

If I may ask, what I'd like to do is have unit tests run on every push everywhere (easy), but also have another set of "checks" i.e. unit tests + espresso tests, full lint etc. but is only relevant before release. i.e. what I used to do locally is have it as

```
task buildAppRelease() {
        group = "build"
        dependsOn ordered(":allClean", ":allTestReleaseUnitTest", "allEspressoTest", ":allLintRelease", ":checkDuplicateStringResourcesAcrossModules", ":app:assembleRelease") 
    }
```
(Nevermind the all prefixes, its because of multi module) and you could also stick deploying at the end also

For my case running these full checks & deploying on every merge into master/release branch feels like a lot? On what event would you hook this up?  Usually locally the signal is "when I know it is ready", but not sure how to do this on CI/CD, since I'm new to it

**Comment by chrisbanes** [comment]
Maybe run the bigger set of checks every night, or every 2 nights or something?

**Comment by ursusursus** [comment]
Now I read what I want is "manual" trigger, which is not available on githu actions (yet?) 
https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504

**Comment by ursusursus** [comment]
Final thing, do you manager versionCode and versionName yourself manually?

**Comment by chrisbanes** [comment]
`versionName` is set in the `build.gradle`. The `versionCode` is just the CI build number, since it's a nice atomically increasing number. It is passed in via a Gradle property on the command line:

`./gradlew bundleRelease assembleRelease -Ptivi.versioncode=$BUILD_NUMBER`

For GitHub Actions, I use the https://github.com/einaregilsson/build-number action.

**Comment by ursusursus** [comment]
I'm wondering if that might not get screwed up with parallel tracks but it looks okay.

Final final thing :D I noticed also you have a separate gradle.properties for CI, 

```
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx5120m
org.gradle.workers.max=2

kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
```

Any reason for the particular settings? daemon=false I get, no reason to start it, but others? why only 2 parallel build workers?

**Comment by ursusursus** [comment]
Also, about dependencies caching, is there any reason you generate cache key per checksum of build files?
https://github.com/chrisbanes/tivi/blob/master/checksum.sh

Can't you you just do what gradle does locally? I.e. look into caches folder and use that if has it. Therefore have a single cache key, and the github cache just collects stuff (and then uses it eviction logic if full)

**Comment by ursusursus** [comment]
About caching, I see you cache dependencies per checksum of gradle build files via
```
done < <(find . -type f \( -name "build.gradle*" -o -name "dependencies.kt" -o -name "gradle-wrapper.properties" \) -print0)
```

however, doesnt that mean that if I change 1 library version in dependencies.kt, all other dependencies are thrown away / redownloaded?

**Comment by chrisbanes** [comment]
No, the cache system has the notion of partial keys when restoring the cache. If there's not a full match it will fall back to the most recent cache.

I'd recommend reading the docs for the Cache action.
